import { Header, Container } from "@/shared/components/shared";
import { Suspense } from "react";

export const metadata = {
  title: "Next pizza | Корзина",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense>
          <Header
            hasSearch={false}
            hasCart={false}
            className="border-gray-200 border-l-0 border-r-0"
          />
        </Suspense>
        {children}
      </Container>
    </main>
  );
}
